    print("Bem-vindo ao Sistema de Análise de Engajamento!")
            print(f"Versão: {self.VERSAO_ANALISE}")
            print("Selecione uma opção:")
            print("1. Cadastrar Plataforma")
            print("2. Listar Plataformas")
            print("3. Gerar Relatório de Engajamento de Conteúdos")
            print("4. Gerar Relatório de Atividade de Usuários")
            print("5. Identificar Top Conteúdos")
            print("0. Sair")